package com.bakalaurinis.model;

public enum InsuranceCategory {
    BROKEN_WINDOWS,
    SMALL_HOLE_CEILING, //50-150
    MEDIUM_LARGE_HOLE_CEILING, //200-400
    REPLACE_CEILING, //
    MINOR_WATER_DAMAGE_CEILING, //200-500
    STRUCTURAL_DAMAGE_CEILING, //2000-8000
    WATER_DAMAGE_HARDWOOD_FLOOR, //8-100 SQFT
    REPLACE_HARDWOOD_FLOOR, //6-23 sqft
    REPLACE_LAMINATE_FLOOR, //3-8
    BURGLARY,









}
